### ISSUE TITLE
How to find key -   command: 'agent -dev -node=learnmicro -client=0.0.0.0 -log-level=INFO'

### ISSUE THREAD

**Issue by andreykirson** [Book-Microservices-v2/chapter08d#1]
Hi, I've tried in cmd to run docker-compose up but received a note :  yaml: line 11: did not find expected key

 line 11 is command: 'agent -dev -node=learnmicro -client=0.0.0.0 -log-level=INFO'   

version: "3"
services:
  consul-dev:
   image: consul:1.7.2
   container_name: consul
   ports:
   - '8500:8500'
   - '8600:8600/udp'
  command: 'agent -dev -node=learnmicro -client=0.0.0.0 -log-level=INFO'
   networks: 
    - microservices
  rabbitmq-dev:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

**Comment by mechero** [comment]
Looks like a problem with YAML parsing, not that command itself. Have you double-checked the indentation? The file is not formatted as code in your question so it's hard to try to figure it out.

**Comment by andreykirson** [comment]
Yes, my mistake.  Sorry to bother you.
